---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwdb-deploy
  namespace: nwns
  labels:
    name: northwinddb
    version: v1

spec:
  # number of pods
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: northwinddb
      version: v1
  template:
  # pod template
    metadata:
      name: nw-pod
      labels:
        name: northwinddb
        version: v1
    spec:
      containers:
        - name: nwdb-container
          image: kubernetes4ts/mysqldb:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: nwdb-secret
                  key: db_password
            - name: MYSQL_DATABASE
              value: "northwind"
          ports:
            - name: mysql
              containerPort: 3306
---
apiVersion: v1
kind: Service

metadata:
  name: nwdb-service
  namespace: nwns
  labels:
    name: nwdb-service
    version: v1

spec:
  type: ClusterIP
  selector:
    name: northwinddb
    version: v1
  ports:
    - name: mysql-port
      port: 3306
      targetPort: mysql
