---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwapp-deploy
  namespace: nwns
  labels:
    name: northwindapp
    version: v1

spec:
  # number of pods
  replicas: 3
  minReadySeconds: 60
  selector:
    matchLabels:
      name: northwindapp
      version: v1
  template:
  # pod template
    metadata:
      name: nwapp-pod
      labels:
        name: northwindapp
        version: v1
    spec:
      containers:
        - name: nwdb-container
          image: kubernetes4ts/webappnw:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nwapp-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: nwapp-config
                  key: DB_USER
            - name : db_password
              valueFrom: 
                secretKeyRef:
                  name: nwdb-secret
                  key: db_password
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: nwapp-port
              containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  name: nwdb-service
  namespace: nwns
  labels:
    name: nwdb-service
    version: v1

spec:
  type: LoadBalancer
  selector:
    name: northwindapp
    version: v1
  ports:
   - name: http
     port: 80
     targetPort: nwapp-port