---
apiVersion: v1
kind: Namespace

metadata:
  name: nwns
  labels:
    version: v1
---
apiVersion: v1
kind: Secret

metadata:
  name: nwdb-secret
  namespace: nwns

data:
  db_password: Y2hhbmdlaXQ= 
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: nwns

data:
  DB_HOST: nwdb-service.nwns.svc.cluster.local
  DB_USER: root