---
apiVersion: v1
kind: Namespace

metadata:
        name: nwdb
        labels:
                version: v1
---
apiVersion: v1
kind: ConfigMap

metadata:
        name: nwapp-config
        namespace: nwdb
data:
        db_password: changeit

---

apiVersion: v1
kind: Secret

metadata:
        name: nwapp-secret
        namespace: nwdb
data:
        db_password: aGVsbG8=

---

apiVersion: apps/v1
kind: Deployment

metadata:
        name: nwdb-deploy
        namespace: nwdb
        labels:
                name: nwdb-pod
spec:
        replicas: 1
        selector:
                matchLabels:
                        name: nwdb
                        version: v1
        template:
                metadata:
                        name: nwdb-pod
                        labels:
                                name: nwdb
                                version: v1
                spec:
                        containers:
                        - name: nw-container
                          image: shilei2991/northwind:v1
                          imagePullPolicy: IfNotPresent
                          env:
                          - name: MYSQL_ROOT_PASSWORD
                            valueFrom:
                                configMapKeyRef:
                                        name: nwapp-secret
                                        key: db_password
                                        
                          ports:
                          - name: mysql-port
                            containerPort: 3306


